#!/bin/bash

#get current user
xbmcUser=$(getent passwd 1000 | sed -e 's/\:.*//')

#configure torrent-transmission
sed -i "s/USER=debian-transmission/USER=$xbmcUser/g" /etc/init.d/transmission-daemon
chown -hR $xbmcUser:$xbmcUser /var/lib/transmission-daemon

#configure sabnzbd
sed -i "s/USER=xbmc/USER=$xbmcUser/g" /etc/default/sabnzbdplus
tar zxvf /usr/share/xbmc/sabnzbd.tar.gz --directory=/home/$xbmcUser/
sed -i "s/home\/xbmc/home\/$xbmcUser/g" /home/xbmc/.sabnzbd/sabnzbd.ini
chown $xbmcUser:$xbmcUser /home/$xbmcUser/.sabnzbd/
/etc/init.d/sabnzbdplus restart

#configure samba
sed -i "s/home\/xbmc/home\/$xbmcUser/g" /etc/samba/smb.conf
sed -i "s/guest account = xbmc/guest account = $xbmcUser/g" /etc/samba/smb.conf

#create shares
if [ ! -d "/home/$xbmcUser/Downloads" ]; then
mkdir /home/$xbmcUser/Downloads
chmod 777 /home/$xbmcUser/Downloads
fi

if [ ! -d "/home/$xbmcUser/Music" ]; then
mkdir /home/$xbmcUser/Music
chmod 777 /home/$xbmcUser/Music
fi

if [ ! -d "/home/$xbmcUser/Pictures" ]; then
mkdir /home/$xbmcUser/Pictures
chmod 777 /home/$xbmcUser/Pictures
fi

if [ ! -d "/home/$xbmcUser/TV Shows" ]; then
mkdir "/home/$xbmcUser/TV Shows"
chmod 777 "/home/$xbmcUser/TV Shows"
fi

if [ ! -d "/home/$xbmcUser/Videos" ]; then
mkdir /home/$xbmcUser/Videos
chmod 777 /home/$xbmcUser/Videos
fi

#copy asroundrc for nvidia ion users
if lspci -nn | grep 'nVidia Corporation ION' &> /dev/null ; then
 cp /usr/share/xbmc/asoundrc-nvidiaion /home/$xbmcUser/.asoundrc
fi

#fix user rights
chown $xbmcUser:$xbmcUser /home/$xbmcUser/ -R
chown $xbmcUser:$xbmcUser /usr/share/xbmc/scripts/XOT-Uzg.v3/ -R
chown $xbmcUser:$xbmcUser /usr/share/xbmc/scripts/BluRay/ -R
chown $xbmcUser:$xbmcUser /usr/share/xbmc/web
chown $xbmcUser:$xbmcUser /usr/share/xbmc/plugins/programs

#mt-daapd
sed -i "s/home\/xbmc/home\/$xbmcUser/g" /etc/mt-daapd.conf
update-rc.d avahi-daemon defaults

#reload modules for makemkv
ldconfig

#fix permissions makemkv
chmod 777 /usr/bin/makemkv
chmod 777 /usr/bin/makemkvcon

#remove runonce
rm -f /usr/share/xbmc/runonce

