#!/bin/sh

GPU=$(lspci -nn | grep 0300)

# 10de == NVIDIA
if [ "$(echo $GPU | grep 10de)" ]; then
 if [ -f /target/boot/grub/menu.lst ]; then
         sed -i -e "/^kernel/s/\(.*\)/\1 xbmc=autostart,nodiskmount,setvolume loglevel=0/ driver=nvidia" /target/boot/grub/menu.lst
         sed -i -e "/^# kopt=root=/s/\(.*\)/\1 xbmc=autostart,nodiskmount,setvolume loglevel=0 driver=nvidia/" /target/boot/grub/menu.lst
 fi
 
 if [ -f /target/boot/grub/grub.cfg ]; then
         sed -i -e "/^ linux/s/\(.*\)/\1 xbmc=autostart,nodiskmount,setvolume loglevel=0 driver=nvidia/" /target/boot/grub/grub.cfg
 fi
else
# 1002 == AMD
if [ "$(echo $GPU | grep 1002)"  ]; then
 if [ -f /target/boot/grub/menu.lst ]; then
         sed -i -e "/^kernel/s/\(.*\)/\1 xbmc=autostart,nodiskmount,setvolume loglevel=0 driver=amd/" /target/boot/grub/menu.lst
         sed -i -e "/^# kopt=root=/s/\(.*\)/\1 xbmc=autostart,nodiskmount,setvolume loglevel=0 driver=amd/" /target/boot/grub/menu.lst
 fi
 
 if [ -f /target/boot/grub/grub.cfg ]; then
         sed -i -e "/^ linux/s/\(.*\)/\1 xbmc=autostart,nodiskmount,setvolume loglevel=0 driver=amd/" /target/boot/grub/grub.cfg
 fi
else
 if [ -f /target/boot/grub/menu.lst ]; then
         sed -i -e "/^kernel/s/\(.*\)/\1 xbmc=autostart,nodiskmount,setvolume loglevel=0 driver=intel/" /target/boot/grub/menu.lst
         sed -i -e "/^# kopt=root=/s/\(.*\)/\1 xbmc=autostart,nodiskmount,setvolume loglevel=0 driver=intel/" /target/boot/grub/menu.lst
 fi
 
 if [ -f /target/boot/grub/grub.cfg ]; then
         sed -i -e "/^ linux/s/\(.*\)/\1 xbmc=autostart,nodiskmount,setvolume loglevel=0 driver=intel/" /target/boot/grub/grub.cfg
 fi
fi
fi

